name: flixel-nx-build

on:
  push:
  workflow_dispatch:
  pull_request:

permissions:
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
        - uses: actions/checkout@v2.3.0
  
    - name: install haxe and shii
      run: | 
        sudo add-apt-repository ppa:haxe/releases -y
        sudo apt-get update
        sudo apt-get install haxe -y
        mkdir ~/haxelib && haxelib setup ~/haxelib
        haxelib git hxcpp https://github.com/retronx-team/switch-hxcpp
        haxelib git ammer https://github.com/retronx-team/switch-ammer
        haxelib install openfl
        haxelib --never install flixel 4.11.0
        haxelib run lime setup flixel
        haxelib run lime setup
        haxelib install flixel-tools 1.5.1
        haxelib install flixel-ui 2.5.0
        haxelib install flixel-addons 2.11.0
        haxelib set flixel 4.11.0
        haxelib set flixel-tools 1.5.1
        haxelib set flixel-ui 2.5.0
        haxelib set flixel-addons 2.11.0
          

    - name: build flixel-nx
      run: | 
        make